---
hide_body: false
is_partial: false
fields:
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- name: summary
  label: Summary
  type: text
  hidden: false
  default: ''
- name: image_preview
  label: Image preview
  type: text
  hidden: false
  default: ''
- name: external_link
  label: External link
  type: text
  hidden: false
  default: ''
- name: math
  label: Math
  type: boolean
  hidden: false
  default: false
- name: highlight
  label: Highlight
  type: boolean
  hidden: false
  default: true
- name: header
  label: Header
  type: field_group
  fields:
  - name: image
    label: Image
    type: text
    hidden: false
    default: ''
  - name: caption
    label: Caption
    type: text
    hidden: false
    default: ''
  hidden: false
  default: 
